### ISSUE TITLE
Compatibility Imagemapping Plugin

### ISSUE THREAD

**Issue by innodan** [turnermm/ckgdoku#12]
Hello,

I like your ckgdoku plugin. It´s really great!

But I use the Imagemapping Plugin ([https://www.dokuwiki.org/plugin:imagemapping]), too. Unfortunately there are some problems. Would it be possible to identify the Imagemapping code while using ckgdoku?

**Comment by turnermm** [comment]
You can use an HTML_BLOCK as described here: https://www.dokuwiki.org/plugin:ckgedit#html_blocks
But you might not be able to use the image mapping plugin, you may have to code the map yourself. Or perhaps you can enclose the plugin output in the HTML_BLOCK
