### ISSUE TITLE
Compatibility with enforcesummary plugin

### ISSUE THREAD

**Issue by innodan** [turnermm/ckgdoku#13]
Hello,

I want to use the enforcesummary plugin [https://www.dokuwiki.org/plugin:enforcesummary]. If I use the DW-Editor, there are no problems. If I use CKGDOKU it does not work. Is there any possibility to use both plugins together?

**Comment by turnermm** [comment]
I've made a few accommodations for other plugins but in this case I suggest you go to the  enforcesummary author,

**Comment by turnermm** [comment]
I may have a solution in the enforcesummary plugin.

**Comment by turnermm** [comment]
I created a pull request to the parent repository (https://github.com/lupo49/plugin-enforcesummary/pull/10).  In the meantime, here is the plugin with my changes; it seems to work without issues:
https://github.com/turnermm/plugin-enforcesummary/archive/master.zip

**Comment by innodan** [comment]
It works fantastic, thanks a lot.

**Comment by turnermm** [comment]
Glad to help.

**Comment by turnermm** [comment]
The pull request has been merged into the [plugin-enforcesummary](https://github.com/lupo49/plugin-enforcesummary) master.
