### ISSUE TITLE
Blank editor screen in Chrome

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#15]
I don`t know why, but since today there is a problem with Chrome. When I open the editor the screen remains empty:
![2017-05-05 15_43_19- spielplatz schutte-wiki](https://cloud.githubusercontent.com/assets/1800472/25747940/9c4599fc-31a9-11e7-9800-54918e43f3c3.png)

**Comment by Juergen-aus-Zuendorf** [comment]
Oh sorry, I've found it:
It was the browser cache

**Comment by s3zwirni** [comment]
Got this error too. In JS-Console this error is visible:

TypeError: editor.lang.geshi is undefined
https://wiki.siedler3.net/lib/plugins/ckgdoku/ckeditor/plugins/geshi/plugin.js?t=G14E
Line 24

Disabling this plugin in config is not successful. I've the languages de-informal and en active.

Any idea?

**Comment by turnermm** [comment]
Update to the latest version.  But for my information I'd like to know what version of ckgdoku you have.

**Comment by turnermm** [comment]
I see the problem.  Please open this as a new issue and then I will get back to you with a solution.
