### ISSUE TITLE
JS-Error with geshi-Plugin

### ISSUE THREAD

**Issue by threadi** [turnermm/ckgdoku#16]
Got the following error in JS-Console after enabling ckgdoku and at start of the editor:

TypeError: editor.lang.geshi is undefined
https://wiki.siedler3.net/lib/plugins/ckgdoku/ckeditor/plugins/geshi/plugin.js?t=G14E
Line 24

Disabling this plugin in config is not successful. I've the languages de-informal and en active.

Any idea?

**Comment by turnermm** [comment]
Please update your ckgdoku. There is now a permanent fix for this problem, just uploaded.  In `ckgdoku/ckeditor/plugins/geshi/lang`, you will find a German lang file with just an entry for `title`, which is the tooltip for the geshi icon in the toolbar.  You can make updates to this file by using the en lang file as yor basis.  If you do, please let me have a copy so I can include it in the distribution.  Thanks.

**Comment by threadi** [comment]
Thx for the fast response. It works :-)

[de.zip](https://github.com/turnermm/ckgdoku/files/980963/de.zip)

**Comment by turnermm** [comment]
Thanks for the German language file.
