### ISSUE TITLE
Ckgeditor doesn't start in firefox

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#18]
Hi,

since yesterday the ckgeditor doesn't start any more in Firefox browser. What can I do?

Regards Juergen

**Comment by turnermm** [comment]
Have you made any changes since yesterday? Try refreshing the browser cache. Go to Options->Privacy.  Or press CTRL+SHIFT+DELETE

**Comment by Juergen-aus-Zuendorf** [comment]
I've made an update of the ckgdoku plugin, and after this I had the described behavior.

Thank you, CTRL+SHIFT+DELETE has solved the problem
