### ISSUE TITLE
Problems while creating internal links

### ISSUE THREAD

**Issue by innodan** [turnermm/ckgdoku#19]
Dear all,

I am using this nice plugin for a longer time. Unfortunately there is some trouble if I want to create an internal links on a sub-ns page: I want to link on a page of the main namespace, but that´s not possible. If I use the link assistent and choose the correct page, dokuwiki places the sub-ns in front of the linked page...

**Comment by turnermm** [comment]
I don't understand this.  Ckgedit creates internal links using the complete namespace:
  `ns1:ns2:ns3:file`
It doesn't matter where you are.  
![2017-06-13 09_55_46-playground_test mturner org](https://user-images.githubusercontent.com/176447/27089170-3e0c4f04-501f-11e7-839f-a867bd567872.png)

**Comment by innodan** [comment]
I hope the following screenshots point up my problem...

Creating the link:
![image](https://user-images.githubusercontent.com/27773617/28917486-1edd43be-7846-11e7-83a6-e8db5feb4dc8.png)

result:
![image](https://user-images.githubusercontent.com/27773617/28917594-7353e6d2-7846-11e7-8b42-50695734fc7f.png)

**Comment by turnermm** [comment]
I'm afraid this doesn't help to understand your problem.  Here is a video showing how to create internal links:
https://www.youtube.com/watch?v=zUS5Qz1rP7U

**Comment by innodan** [comment]
I know how create links und i do it excactly as shown in the video but it doesn´t work. :(

I want to link the page "start" on my page called pb:test. But the link is not to the page "start" but to the page "pb:start". So the editor writes the current namespace in front of the name of the linked page. This is why I can not link to pages of the root-namespace oder any other namespaces...

I hope this explanation will help you to understand my problem...

**Comment by turnermm** [comment]
Install and test this using the manual tab of the extension manager:
https://github.com/turnermm/ckgdoku/archive/ilinkt.zip

**Comment by turnermm** [comment]
The above assumes that any link without an initial colon is a member of the current namespace,  So if you are currently in the` :devel` namespace, the following  `faq:tools` will give you `:devel:faq:tools`.  The following:  `:faq:sidebar`  will assume that faq is a namespace in the root directory and `:start` is a page in the root directory, whereas `start` is a page in the current namespace.

**Comment by innodan** [comment]
Sorry, but it does not work... :(

The problem exists nonetheless.

Are any incompatibilities with any other plugins known?

**Comment by turnermm** [comment]
It's been tested in both FF and Chrome multiple times. Clear your browser cache. Use another browser, also clear its cache.  Are you using https://github.com/turnermm/ckgdoku/archive/ilinkt.zip ?

http://www.youtube.com/watch?v=omDA6S0w0w0
This clip starts out by showing you that you are in the playground namespace, creates an internal link in the root directory named `:intro`, then an internal link named `links`, which without the leading colon is created as `:playground:links`.  Then it switches to the browser and shows that these links work.

**Comment by innodan** [comment]
It works... Thanks a lot!

**Comment by turnermm** [comment]
I've merged it into the master.
