### ISSUE TITLE
Upload of non-image files is not possible with mediamanager action

### ISSUE THREAD

**Issue by albig** [turnermm/ckgdoku#2]
Thanks for your work to include dokuwiki mediamanager into ckgedit.

In dokuwiki you limit the uploads by conf/mime.conf. So uploading of PDF or DOC-files is ok. The dokuwiki mediamanager is called by the icon "add image or other files". In CKedit there seems to be only a button "image". Both call the dokuwiki mediamanager when using ckgdoku. But with ckgdoku installed, there is always an error message
`Upload only images when using image dialog: application/pdf`
when uploading e.g. PDF files.

The reason for this is based on a condition in your action:
`action/mediamanager.php`
This hook is also active, if you use the default dokuwiki editor.

This is not perfect. Dokuwiki allows PDF but ckgdoku denies everything except images. 

**How can users upload other files with ckgdoku?** 

Maybe I'm blind but there seems to be no possibily.

**Comment by turnermm** [comment]
This has to do with the limitations of the image dialog.  It can  handle only images.  So if you want to upload any other kinds of media files, you have to use the link dialog, selecting the internal media option.   Perhaps the message shoud be made clearer.

**Comment by turnermm** [comment]
I just changed the error message to read: `Use the link dialog's internal media option to upload non-image files`
