### ISSUE TITLE
Connection cells at the end of a table

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#20]
Hi,

when I join two cells in a table together which are in the last row, the table becomes corrupted. 

_Example:_
The following syntax
```
|  Einstellungen            ||  Datum / Name  |
|  Sollwert       | Istwert  | :::            |
```
is converted by CKGedit to
```
|  Einstellungen  ||  Datum / Name  |
|  Sollwert  |Istwert  |
```
The flag "complex tables" is set.

Regards
Juergen

**Comment by turnermm** [comment]
See: https://www.dokuwiki.org/plugin:ckgedit#html_blocks
The one drawback of this method is that you can't conveniently edit the  table in the native dokuwiki editor.

**Comment by Juergen-aus-Zuendorf** [comment]
The problem is that the ckgeditor is especially for users which normally use text editors like word and which have no knowledge of programming html

**Comment by turnermm** [comment]
They don't have to program HTML. Just use the macros.  Most tables work without the HTML macros.

**Comment by Juergen-aus-Zuendorf** [comment]
Ok, thank you! Now I understand. I'll try it.
