### ISSUE TITLE
Wrong formatting in table cells after editing

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#22]
Hi,

first I have a table like this:
![2017-07-04 14_43_15- spielplatz schutte-wiki](https://user-images.githubusercontent.com/1800472/27830603-73d48616-60c7-11e7-905d-515273285449.png)

Then I edit a cell in the second row and column by inserting a text in a further line (with hard return):
![2017-07-04 14_43_37- spielplatz schutte-wiki](https://user-images.githubusercontent.com/1800472/27830624-8a27a93e-60c7-11e7-99fd-98905c28714f.png)

In the CKGDoku editor all looks fine, but the result is that after saving this edited cell has a wrong orientation:
![2017-07-04 14_43_53-spielplatz schutte-wiki](https://user-images.githubusercontent.com/1800472/27830642-a2d948de-60c7-11e7-8f3b-0b8988fb664d.png)

Best regards
Juergen

**Comment by turnermm** [comment]
Use hard return and also see this:
https://github.com/turnermm/ckgedit/issues/285

**Comment by turnermm** [comment]
A hard return is SHIFT+ENTER, not just ENTER.
Your illustration seems to show an ordinary ENTER which in CKEditor gives you a new paragraph.

The other thing you can do is, after re-loading,  click on the cell and go to cell properties and selecte the alignment.

**Comment by Juergen-aus-Zuendorf** [comment]
Oh, yes, I mean "Enter" without Shift.
