### ISSUE TITLE
[Feature Request] more protocols for links

### ISSUE THREAD

**Issue by l0wBoB** [turnermm/ckgdoku#23]
Hi,
would it be possible to add more protocols for url-links?
Especially ssh: and tel: would spare me and my colleagues a lot of customization in the source code.
Thank you for your work.

**Comment by turnermm** [comment]
I've fooled with it and it's easier said than done.

**Comment by turnermm** [comment]
Here is what I suggest:
Go to ckgdoku/ckeditor/plugins/link/dialogs
Open link.js.unc.  At line 619 you'll find:

items :
[
    [ 'http://\u200E', 'http://' ],
    [ 'https://\u200E', 'https://' ],
    [ 'ftp://\u200E', 'ftp://' ],
    [ 'news://\u200E', 'news://' ],
    ck_m_files_protocol
],


Add your own protocols:

items :
[
    [ 'http://\u200E', 'http://' ],                                            
    [ 'https://\u200E', 'https://' ],
    [ 'ftp://\u200E', 'ftp://' ],
    [ 'news://\u200E', 'news://' ],
    [ 'ssh://\u200E', 'ssh://' ],
    [ 'tel://\u200E', 'tel://' ],
    ck_m_files_protocol    
],


Now you can do one of two things,  You can simply rename the .js.unc file to .js or you can compress it, using the instructions found here:  https://www.dokuwiki.org/plugin:ckgedit#compression.
If you use linux, then this script will do the job:

```
#!/bin/sh
IN=$1

if [ "$2" ]
then
OUT=$2
else
BASENAME=` echo $1 |  awk -F. '{ print $1 }' `
EXTENSION=` echo $1 | awk -F. '{ print $2 }' `
echo $BASENAME
OUT="$BASENAME-cmpr.$EXTENSION"
fi
echo $OUT
YUI=/usr/lib/jvm/yui/yuicompressor
java  -jar $YUI --type $EXTENSION $IN -o $OUT


```
YUI is wherever you keep the jar file.  This will create a compressed file named link.cmpr.js, which has to be renamed to link,js

**Comment by l0wBoB** [comment]
Thanks, I will try that.

**Comment by l0wBoB** [comment]
This doesn't seem to work just yet.
I added the lines and renamed the file after taking a backup of the original ones.
The new protocols appear in the editor and are written as correct href-links in the source code.
But once the site is saved, they are automatically altered which breaks them.

For example, this is generated by the editor:
`<a href="ssh://1.2.3.4">ssh-link</a>`
And this is what is in the code after saving:
`<a class="wikilink2" href="/doku.php?id=walz:ssh-link" rel="nofollow" title="walz:ssh-link">ssh-link</a>`

Note: "walz:" is the category the page is in. (http://mywiki/doku.php?id=walz:examplepage)

The original protocol-links like http are not altered upon saving.

A working tel:-link appears like this in the source code:
`<a class="interwiki iw_tel" href="tel:oIWIKIo+4924151537391cIWIKIc" title="tel:oIWIKIo+4924151537391cIWIKIc">+49 241 51537391</a>`

**Comment by turnermm** [comment]
At the risk of  asking the obvious, have you added  the schemes to conf/scheme.conf?

**Comment by turnermm** [comment]
And what do you find in the Dokuwiki editor after a save?  You should find: `[[ssh://url]]`

**Comment by turnermm** [comment]
These work for me.
[link.zip](https://github.com/turnermm/ckgdoku/files/1193919/link.zip)

**Comment by l0wBoB** [comment]
I added the two protocols to scheme.conf also but the problem persists. :(

URL-link created via ckgdoku editor: `tel://123456`
source code: `<a href="tel://123456">123456</a>`
source code after saving: `<a class="wikilink2" href="/doku.php?id=namespace:123456" rel="nofollow" title="namespace:123456">123456</a>`
code in dw-edit: `[[:namespace:123456|123456]]`

Am I missing another step besides modifing link.js.unc/link.js and scheme.conf?

**Comment by turnermm** [comment]
[[wrong file]]

I updated link.js.  I see that you are using interwiki links to create the phone entry.  You can do that with the interwiki feature of the link dialog.  But because of a change I had made to conform to current standards, I found that the interwiki selections weren't loading quickly enough.

**Comment by turnermm** [comment]
Above fixed

**Comment by l0wBoB** [comment]
Thank you!
