### ISSUE TITLE
moono-lisa option?

### ISSUE THREAD

**Issue by jobhh** [turnermm/ckgdoku#28]
moono-lisa is the default skin of CKEditor 4 since version 4.6. I haven't found an option to enable it in Dokuwiki, even though the moono and moono-lisa files seem to be included with ckgdoku.

I changed moono to moono-lisa in these config files and it works fine (see screenshot):
- config.js
- config.js.unc

To keep this I'd have to edit these files with every update of ckgdoku. Would it be possible to add a skin selection option to the Dokuwiki Configuration Settings?

![image](https://user-images.githubusercontent.com/2331451/29519219-d9c5add0-867c-11e7-8e60-261587c4cda7.png)

Also a quick question:
The changelog of Jun4 states the following:

    Switching to tag 'current' as Dokuwiki download version

But with the last update it reverted to 'master', was this by design?

**Comment by turnermm** [comment]
Good idea.  There's now a config option for switching between skins.

**Comment by jobhh** [comment]
Thank you, it seems to be working :)

I was also wondering why the changelog of Jun4 states the following:

    Switching to tag 'current' as Dokuwiki download version

But it seems to be reverted to 'master', was this by design?

**Comment by turnermm** [comment]
Just an oversight.
