### ISSUE TITLE
Mailto by URL as HTML-code

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#29]
Hi,

is there a possibility to embed such a code to enable a symbol with a mailto function:

``
[[mailto:hans-juergen.schuemmer@schuette.de?subject=Kundenmitteilung%20TM00049&body=Hallo Kollegin/Kollege,%0D%0Dbitte%20die%20Technische%20Kundenmitteilung%20TM00049%20verarbeiten:%0Dhttp://appsrv03/wiki/doku.php?id%3Dtechnik:mitteilungen:tc:2017:techn-mitteilung_00049:techn-kundenmitteilung%0D%0DViele Gr%C3%BC%C3%9Fe%0DHolger%20Pasligh|{{  :symbole:alg:email.png|Mail erzeugen}}]]
``

I`ve tested it with START_HTML_BLOCK / CLOSE_HTML_BLOCK, but it doesn't work because the html code is interpreted by the editor

Regards
Juergen

**Comment by turnermm** [comment]
That's because it's not HTML.
```
~~START_HTML_BLOCK~~
<a href="mailto:hans-juergen.schuemmer@schuette.de?subject=Kundenmitteilung%20TM00049&body=Hallo Kollegin/Kollege,%0D%0Dbitte%20die%20Technische%20Kundenmitteilung%20TM00049%20verarbeiten:%0Dhttp://appsrv03/wiki/doku.php?id%3Dtechnik:mitteilungen:tc:2017:techn-mitteilung_00049:techn-kundenmitteilung%0D%0DViele Gr%C3%BC%C3%9Fe%0DHolger%20Pasligh">Image</a>
~~CLOSE_HTML_BLOCK~~

```

**Comment by turnermm** [comment]
And don't forget to enable HTML blocks in the Configuration Manager.

**Comment by Juergen-aus-Zuendorf** [comment]
Thank you very much!
