### ISSUE TITLE
Copy & paste in a table

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#31]
Hi,

when I write a text into a cell of a table, its not possible to copy this text some times into this same cell. When pressing Ctrl/V, always the whole content of the cell is replaced

Example:
![grafik](https://user-images.githubusercontent.com/1800472/32840562-4ac7db96-ca18-11e7-907b-8f613bfdd199.png)

The word "Testtext ->" has to be copied several times, so at the end the table should look like this:
![grafik](https://user-images.githubusercontent.com/1800472/32840582-5c078f5a-ca18-11e7-8df7-dc881169b56f.png)

But every time I paste the content of the clipboard the content of the cell is completely replaced by the text of the clipboard:
![grafik](https://user-images.githubusercontent.com/1800472/32840598-69c5bd10-ca18-11e7-9306-840022e7e3d3.png)

Best regards
Juergen

**Comment by turnermm** [comment]
This is a CKEditor issue.  You might be able to report this to them and have it fixed in a future  distribution of the CKEditor.

**Comment by Juergen-aus-Zuendorf** [comment]
Hi,

the problem seems to be solved:
https://github.com/ckeditor/ckeditor-dev/issues/1178#issuecomment-350718803

Could you please provide it in one of your next releases?

Best regards
Juergen

**Comment by turnermm** [comment]
Moving up to the next release of CKEditor is always a lot of work.  This issue can be handled in the current release by a simple use of a space.  First of all, there is no problem  inserting after the current text.  

The only issue is inserting before the current text.  If you first insert two spaces before the current text and then insert the additional text, both insertions remain in place.  The extra space ends up in front of the new insertion.  That extra space in front of the new insertion does not count if you want to insert a new text in front of that one: you must still insert two new spaces at the beginning of the insertions  and you always end up with one space before and one after the next insertion.

**Comment by Juergen-aus-Zuendorf** [comment]
Puh, that's difficult to communicate! A user who chooses the ckgeditor wants a simple to use editor. On the other hand the problem described in my issue is very specific. 

So, my only request is to have this somewhen in future.

**Comment by turnermm** [comment]
Too difficult to learn to insert 2 spaces?

**Comment by turnermm** [comment]
I am working on a merger of ckgedit with ckgdoku, so that once complete, there will only be one ckgedit and no ckgdoku.  The most recent version of this merger updates the CKEditor to 4.9.:
  https://github.com/turnermm/ckgedit/archive/merger.4.9.zip
You might see if this solves the problem you were having.
