### ISSUE TITLE
Deleting page when changing the editor height

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#35]
When I set a new value for the editor hight and press enter, there comes up a window to delete the page:
![grafik](https://user-images.githubusercontent.com/1800472/33161992-54410750-d027-11e7-8d69-174901601ba4.png)
![grafik](https://user-images.githubusercontent.com/1800472/33161997-5ee253f8-d027-11e7-877f-22f182fe288f.png)

If I'm not careful enough and I press enter again the page is really deleted. So it would be better to set the focus to another button or into the editor's area (if possible) after setting a new value.

Regards Juergen

**Comment by turnermm** [comment]
Hmmm?  I don't get this.  Which button do you press when  you leave the page?  It should be OK with  `Cancel` or `Save`.

**Comment by Juergen-aus-Zuendorf** [comment]
It's only the "Enter" on the keyboard which is unconsciously pressed to confirm the input of a new value

**Comment by turnermm** [comment]
Try the latest update.

**Comment by turnermm** [comment]
Try the lastest ckgdoku update

**Comment by Juergen-aus-Zuendorf** [comment]
Sorry, but I have already installed the version "2017-10-26", and there is no newer one available at https://www.dokuwiki.org/plugin:ckgdoku

**Comment by turnermm** [comment]
This was fixed in https://github.com/turnermm/ckgdoku/commit/5f8b22772bb4de1ee8cf9bbf1fc37cc4c1977885 on Nov 24.
