### ISSUE TITLE
Interwiki links

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#36]
In `interwiki.local.conf` I've defined interwiki links. But they are interpreted wrong when using ckgdoku:

_Before:_
[[easydm.asd.00>RBU1430510]]

_After using ckgdoku:_
[[:playground:easydm.asd_00_oiwikiodefault.htm?sap-sysname=PRD&easydms-dokar=ASD&easydms-doknr=RBU1430510&easydms-doktl=001&easydms-dokvr=00cIWIKIc|RBU1430510]]

The key `easydm.asd.00` is defined as `http://v-sapprd.ahs.local:8000/EDM/default.htm?sap-sysname=PRD&easydms-dokar=ASD&easydms-doknr={NAME}&easydms-doktl=001&easydms-dokvr=00`

Best regards
Juergen

**Comment by turnermm** [comment]
Change your iwiki label to one with only a single extension:  `easydm.asd.00` to `easydm.asd`

**Comment by Juergen-aus-Zuendorf** [comment]
Ok, thank you!

**Comment by turnermm** [comment]
I think I've fixed this so that multiple extensions can be used.  See:
https://github.com/turnermm/ckgdoku/archive/iwiki_update.zip

**Comment by Juergen-aus-Zuendorf** [comment]
Thank you, but that does'nt work. The second dot is replaced by an underscore.

One more little thing:
The interwiki link has a symbol like this:
![grafik](https://user-images.githubusercontent.com/1800472/33650182-2ffbd6e2-da61-11e7-99ac-1500631c9854.png)
In the ckgeditor it moves to this:
![grafik](https://user-images.githubusercontent.com/1800472/33650193-3c564792-da61-11e7-81b0-7b835fa2db2a.png)

**Comment by turnermm** [comment]
> Thank you, but that does'nt work. The second dot is replaced by an underscore.

give me your example, because all my tests work, as long as the extensions are more than one character:
   `ab.cd.ef`
Perhaps it's a caching problem. Refresh your browser and dokuwiki caches.

**Comment by Juergen-aus-Zuendorf** [comment]
Ok, thank you! It really was a cache problem, and after a long weekend it works.

What's about the symbol in front of the link? Is there a chance to change it to the right one?

**Comment by SergeySCHU** [comment]
I also have a problem with Interwiki link
In interwiki.local.conf, I added link the `qs   :ru:dev:core:`
Then on the page I inserted the link [[qs> quickstart]] saved it.
As a result, I received a link: `:ru:dev:core:quickstart` and this is exactly what I wanted.
But if you just open and save the page, the link will change to `:ru:dev:core:doku.php`

**Comment by turnermm** [comment]
I think it should be OK now.

**Comment by SergeySCHU** [comment]
Thanks, now it works correctly.

**Comment by Juergen-aus-Zuendorf** [comment]
Excuse me, once more my question about the symbols:

The interwiki link has a symbol like this:
![grafik](https://user-images.githubusercontent.com/1800472/34478471-7092a0dc-efa1-11e7-9143-fa9a40d2e7e9.png)

In the ckgeditor it moves to this:
![grafik](https://user-images.githubusercontent.com/1800472/34478501-76f6c16a-efa1-11e7-9ace-5d8998aeb9c5.png)

**Comment by turnermm** [comment]
That is just a place holder. To have your icon show up in the CKEditor, you wouold have to code the CKeditor's css for this and add the image to the fileicons directory, which is `ckgdoku/ckeditor/images/fileicons`.  The uncompressed css is in `contents.css.unc`. You add your css there and the recompress it to `contents.css`

**Comment by Juergen-aus-Zuendorf** [comment]
Ok, thank you.
It looks a little bit complicated for me, but I'll try it.

Why is the missing symbol replaced by the wikipedia-symbol?

**Comment by turnermm** [comment]
No real reason.
