### ISSUE TITLE
URL processing bug

### ISSUE THREAD

**Issue by jobhh** [turnermm/ckgdoku#37]
A user pasted a l.facebook URL in a page and saved it. When another used edited that page with ckgdoku that URL got misformed, while the user didn't edit that line. I've recreated the bug with a similiarly formed URL.

I created a page with this source:
`[[https://​l.facebook.com/​l.php?​u=https://test.com|https://test.com]]`

Which looks like this outside of the editor:
![image](https://user-images.githubusercontent.com/2331451/33612067-c3e2143e-d9d0-11e7-9025-b6a9177a13db.png)

When I wrote a line below that URL, so I didn't touch the line itself, it seemed fine in ckgdoku. However, after saving the source of the original line became:
`[[https://​​l.facebook.com/​​l.php|]]`

Which looks like this outside of the editor:
![image](https://user-images.githubusercontent.com/2331451/33612049-b010164a-d9d0-11e7-9992-4061a88e5910.png)

Sooooo,
`?​u=https://test.com` and `https://test.com` seem to be removed. Or maybe the question mark became a pipe and the rest was omitted?

**Software versions**
Dokuwiki 2017-02-19e “Frusterick Manners”
I updated ckgdoku on 2017-12-01 and since the latest commit was on 2017-11-28 it's the latest version. Even though dokuwiki claims the latest version is 2017-10-26 (see #38)

**Comment by turnermm** [comment]
Can't reproduce this.

**Comment by jobhh** [comment]
I just made a new Dokuwiki install with only ckgdoku installed to test it. The issue also exists on this clean install.

I've giving edit rights to ALL on this page. HOST/dokuwiki/doku.php?id=ckgdokubug
Between these edits I only changed the number 1 into a 2, but ckgdoku also changed the URL: HOST/dokuwiki/doku.php?id=ckgdokubug&rev=1512491650&do=diff

Steps:
1. Paste `[[https://​l.facebook.com/​l.php?​u=https://test.com|https://test.com]]` with the DW editor
2. Save the page
3. Now edit the page with ckgdoku. You can't only open and save it, you'll have to edit something (create a new line with a dot or something)
4. Save the page, done.

**Comment by jobhh** [comment]
Another bug I just noticed. I assume this is a Dokuwiki bug and not ckgdoku.
The italic text in this page escapes the page content and makes the side menu and footer also italic... HOST/dokuwiki/doku.php?id=start 😛

**Comment by turnermm** [comment]
Your last "bug" seems to be a syntax error on your part.

The other issue is fixed, and just recently crept in when we added support for relative links.

**Comment by jobhh** [comment]
I can confirm that the URL processing bug is fixed. Thanks :)

True, that's a syntax error. I just assumed that Dokuwiki would restrict my syntax to the page content. It seems odd that page content can alter the content outside of the page. But that doesn't happen I just noticed.

The way that syntax got there does seem to be a ckgdoku bug though. That page's content was edited in ckgdoku when it changed from `[[https://​​l.facebook.com/​​l.php?​​u=https://​test.com|https://​test.com]]` to `''​https://​​l.facebook.com/​​l.php?​​u=https://​test.com''`. However, I don't remember how it happened exactly. Maybe it's already fixed in the last commit. I'll let you know if I ever reproduce it.


Apart from ckgdoku, I do wonder why Dokuwiki renders `''​https://​​l.facebook.com/​​l.php?​​u=https://​test.com''` in a way the sidebar and footer become italic. It has an even number of `//`'s, both after a https:, but the second `//` seems to be ignored.

**Comment by turnermm** [comment]
Your example page previously was missing the opening `''`

**Comment by jobhh** [comment]
I'm not sure how to interpret this, is it in response to the italic example page?

The start page HOST/dokuwiki/doku.php?id=start has this as source:
`''​https://​​l.facebook.com/​​l.php?​​u=https://​test.com''` 

Which is rendered by Dokuwiki as this:
![image](https://user-images.githubusercontent.com/2331451/33667798-1e1a2158-da9e-11e7-80ff-497001ab5dab.png)

Can you explain this or shall I open an issue at dokuwiki?

**Comment by turnermm** [comment]
Dokuwiki is interpreting the two sets of forward slashes as markup:
 `  https://​l.facebook.com/​l.php?​u=https://test.com`
If you recast it as follows, you will not have that problem:
`  [[https://​l.facebook.com/​l.php?​u=https://test.com|facebook]]`

Try it yourself, not in the ckgdoku editor, but in the native dokuwiki editor and use the preview to check the result.

**Comment by turnermm** [comment]
An d wither of these will work:
If you want the full text of the link:
`[[https://​l.facebook.com/​l.php?​u=https://test.com]]  
`
If you don't want it to be a link:
`%%https://​l.facebook.com/​l.php?​u=https://test.com%%`
