### ISSUE TITLE
Update URL problem (master.zip)

### ISSUE THREAD

**Issue by jobhh** [turnermm/ckgdoku#38]
I find it odd that the update URL of ckgdoku in Dokuwiki is https://github.com/turnermm/ckgdoku/archive/master.zip. 

Dokuwiki only mentions a new version when you release one, but when someone clicks the update (or re-install) button they get the latest commit in the repository and not the version you marked for release. This means we're currently running a version that wasn't meant for release yet, making us unintentional beta testers 😀.

It was mentioned in september https://github.com/turnermm/ckgdoku/issues/28#issuecomment-327030980 that there was an oversight with the update URL, but I don't know if the master.zip URL is the oversight or the fix for the oversight.

I'd like to suggest to have an update URL that downloads the latest release version, in stead of the latest commit version.

**Comment by turnermm** [comment]
> his means we're currently running a version that wasn't meant for release yet, making us unintentional beta testers

Not the case.  Plugins are generally updated on a continuing basis.  Whatever is slotted for download is the current version, no matter what the extension manager says.

**Comment by jobhh** [comment]
Ok :) Thanks for the clarification.

Followup question: If I edit the "Last updated on" on https://www.dokuwiki.org/plugin:ckgdoku after a update on github, will that result in an update notification for the users of ckgdoku? Or does the plugin author have to edit something? In other words: How does the Dokuwiki update notification system work?

Right now it seems odd people would run a 2 month old version, if the latest version is production ready. Without a update notification most people won't update and miss out on the bug fixes. For example, this person two days ago https://github.com/turnermm/ckgdoku/issues/35#issuecomment-348886852 didn't know there was an update newer than 2017-10-26.

**Comment by turnermm** [comment]
> if the latest version is production ready.

This is not Microsoft or Mozilla or even Dokuwiki core.  Plugin authors are individuals, volunteers, not groups of developers.  If someone opens an issue, the author tries solve it and when it seems solved, updates the plugin code and posts a new date to the plugin page and a new date in the plugin's version file.  Then the user is notified of a new version. Sometimes this doesn't get done.  In the case you are referring to, the user's issue had already been addressed, and there was no new version.

**Comment by jobhh** [comment]
Please don't take my questions as an attack or criticism, I'm seriously interested. 

My question was: If I update the "Last updated on" on the https://www.dokuwiki.org/plugin:ckgdoku page, is that what is used by Dokuwiki to show the update notification to people who have the plugin installed?

Because then I can just update that page when I notice an update notification is due (and the version/plugin.info.txt/Changes have been updated already).

**Comment by turnermm** [comment]
An update notification will appear in the Extension Manager when the date on the plugin page at dokuwiki.org has been updated.  You have to check the Extension Manager periodically.  You shouldn’t have to worry about checking plugin.info.txt.  If you check the “Last udated” and see there is an update that you Haven’t been notified of, then you can use the reinstall button in the Extension Manager.
