### ISSUE TITLE
Table with listings

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#40]
The ckgeditor allows to put a list into a cell of a table:
![grafik](https://user-images.githubusercontent.com/1800472/33828194-714d688c-de6b-11e7-8290-7082b761c488.png)

But the dokuwiki syntax doesn't support this. So the syntax after saving is corrupted:
![grafik](https://user-images.githubusercontent.com/1800472/33828228-8db86fb2-de6b-11e7-8cdf-06419e853eb6.png)

Therefore, because it's not possible in dokuwiki it also shouldn't be allowed in the editor.

Regards Juergen

**Comment by turnermm** [comment]
I have no plans for that, since it's possible to use do this nevertheless, using the HTML_BLOCK macros.  And some knowledge of dokuwiki is always helpful when using dokuwiki.

**Comment by Juergen-aus-Zuendorf** [comment]
Ok, I'll try to give some hints to the users, and I hope that they will remember this

**Comment by turnermm** [comment]
When you use the HTML_BLOCK macros, you can still edit and then re-save the table at a later time.

**Comment by Juergen-aus-Zuendorf** [comment]
Ok, but in this case the code isn't yet changeable by the native editor any more.

**Comment by turnermm** [comment]
That’s true.  Or else you can give up the list.

**Comment by Juergen-aus-Zuendorf** [comment]
Thank you!
That's right. You can not have everything :)
