### ISSUE TITLE
Copy&paste of media in Chrome

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#41]
When I copy some content of one wiki page and insert it into another page the included pictures are partially converted to mysterious links:

1.) after pasting into the editor:
![grafik](https://user-images.githubusercontent.com/1800472/33828447-7df3bb4e-de6c-11e7-847d-85ca08955a8c.png)

2.) the result in the browser:
![grafik](https://user-images.githubusercontent.com/1800472/33828473-8fd7e0e2-de6c-11e7-88c1-26acf5e7c742.png)

The syntax after saving:
```
====   ]]  ====

{{:redaktionssystem:techn_doku:00017_p001:9d9114969b9beff859da4e628c70d5b4.png?847x847 ]] [[{{:redaktionssystem:techn_doku:00017_p001:ba40d366c9db502b78614d471dfe94fe.png}}
```
It seems that this is only a problem of Chrome

Regards
Juergen

**Comment by turnermm** [comment]
I had no trouble with this image.   It could be a matter of resources, memory. 
https://www.dokuwiki.org/plugin:ckgedit#copy_and_paste

**Comment by Juergen-aus-Zuendorf** [comment]
Switching the flag "supplementary image paste support" on or off has no effect on this. And the problem exists both in the browser of my colleague and in my chrome browser. We use version Chrome 63.0.3239.84 on a win7 system.

**Comment by turnermm** [comment]
I'm afraid I haven't reproduced this.  And the fact t hat you are getting it with and without the flag suggests some kind of glitch in your setup and perhpas a lack of resources.  This is a very large image.  Do you get it with all images?
I use Chrome: 63.0.3239.84 (Official Build) (64-bit).  
Here it is loaded intto Dokuwiki:
![playground_copy_im](https://user-images.githubusercontent.com/176447/33888038-68bad370-df11-11e7-81af-259ff23b93f1.png)

**Comment by Juergen-aus-Zuendorf** [comment]
I get it even with this, although with another misfeature:
![grafik](https://user-images.githubusercontent.com/1800472/33893693-601a4066-df5c-11e7-9a35-3ddf8480b252.png)
... with this HTML-code:
```
<h1 class="page-header">Spielplatz</h1>
<div class="level1">
<p><a class="media" href="/wiki/lib/exe/fetch.php?media=symbole:alg:achtung.jpg" rel="noopener" target="_blank" title="symbole:alg:achtung.jpg"><img alt="achtung.jpg" class="medialeft" height="42" src="/wiki/lib/exe/fetch.php?w=42&amp;h=42&amp;tok=4307e1&amp;media=symbole:alg:achtung.jpg" title="achtung.jpg" width="42" /></a><a class="media" href="/wiki/lib/exe/fetch.php?media=symbole:alg:auto.png" rel="noopener" target="_blank" title="symbole:alg:auto.png"><img alt="" class="medialeft img-responsive" height="40" src="/wiki/lib/exe/fetch.php?w=40&amp;h=40&amp;tok=039a59&amp;media=symbole:alg:auto.png" width="40" /></a></p>
</div>

```
After saving the new page the pictures are lost:
![grafik](https://user-images.githubusercontent.com/1800472/33893987-1725fb38-df5d-11e7-9659-cdeec2a3a8ac.png)

The HTML code looks like this:
```
<h1 class="page-header">Spielplatz</h1>
<div class="level1">
<p><a class="wikilink2" href="/wiki/doku.php?id=symbole:alg:auto.png" rel="nofollow" title="symbole:alg:auto.png">auto.png</a></p>
</div>
```

_To avoid misunderstanding:_
I open the CKEditor of the old page, copy the content into clipboard and then paste this into the CKEditor of the new page

**Comment by turnermm** [comment]
I’m afraid I can’t help you, because I can’t reproduce your issue.  And, I don’t really follow you. Where does the HTML come in?  The image data should be copied to the clipboard

**Comment by Juergen-aus-Zuendorf** [comment]
Ok

I have a page called "playground", and I want to create a new page called "playground1":
![grafik](https://user-images.githubusercontent.com/1800472/33895308-875743a0-df60-11e7-8a9e-199a9b7fdbb6.png)

Now I copy the content of playground and paste it to playground1:
![grafik](https://user-images.githubusercontent.com/1800472/33895388-af7d2a16-df60-11e7-9dd4-7627291f4a13.png)

Then I save playground1, and the result is this:
![grafik](https://user-images.githubusercontent.com/1800472/33895429-c86032ee-df60-11e7-92d6-e17e79fc5ba7.png)

The comparison of the both pages is that the HTML-codes now are totally different:
![grafik](https://user-images.githubusercontent.com/1800472/33895523-fe8f585e-df60-11e7-8fa7-c600b56f7dcd.png)

**Comment by turnermm** [comment]
I don't know what is happening on your site.  I have copied and pasted an image from one page to another and one page in namespace 1 to another page in namespace2.  The HTML code is copied and the image reproduced without issue.

**Comment by turnermm** [comment]
I see what is happening.  You are copying the HTML code into the clipboard, but the HTML code includes a link to the detail page.  And when the coy is made and pasted, you are getting malformed a link to the  detail instead of the image,

So if you want to cop;y and paste from one dw page to another, you have to first removed the detail.  You can do this by right-clicking on the image and removing the detail attribute.

**Comment by Juergen-aus-Zuendorf** [comment]
The media of both pictures is defined as "direct":
![grafik](https://user-images.githubusercontent.com/1800472/33927203-a5ff8106-dfe1-11e7-8a29-e22cd2c15371.png)

But I have the problem

**Comment by turnermm** [comment]
Direct is the DW default.  So is ckgedit’s. It’s a simple matter to change it.

**Comment by Juergen-aus-Zuendorf** [comment]
Sorry, but it doesn't yet work. And also after the update to the current version of ckgedit the problem remains. 

The dokuwiki code of the old page is
```
====== Spielplatz 1 ======

{{:symbole:alg:achtung.jpg?direct&|achtung.jpg}}{{:symbole:alg:auto.png?direct&}}
```
(with the included "?direct" command)

I open the CKEditor of this old page, copy the content into clipboard and then paste this into the CKEditor of the new page.

Then on saving the code is spoiled. It changes to
```
====== Spielplatz 2 ======

[[{{:symbole:alg:auto.png|]]
```

**Comment by turnermm** [comment]
If I put two images next to each other in the editor, highlight the images, press Ctrl-C (in Windows/Firefox),  then when I paste it into another page using Ctrl-V, I get the exact same dokuwiki markup.  In Chrome, I get your result.  There's nothing I can do abut this.  However, if in Chrome you close the edtior and copy from the browser, you will not get the same markup in the paste, but you will get the same result in the browser.

**Comment by Juergen-aus-Zuendorf** [comment]
Your suggestion for Chrome to copy from the browser and paste into the editor leads to this:
![grafik](https://user-images.githubusercontent.com/1800472/34483451-d745460a-efbe-11e7-98f5-431767382108.png)
... with the resulting wiki syntax:
```
====== Spielplatz 2 ======

[[http://appsrv03/wiki/lib/exe/fetch.php?media=symbole:alg:auto.png|{{:symbole:alg:auto.png?direct&}}]]
```
As you can see the first picture (exclamation mark) is deleted, and the wiki path to media of the second picture (car) is converted to an URL.

**Comment by turnermm** [comment]
There's nothing I can do about this.  Ckgdoku/ckgedit are not designed to be HTML to Dokuwiki converters. This is not the only HTML that cannot be pasted into the editor with  successful results.    If this is important to you, then you can open the dokuwiki editor and paste the dokuwiki markup into the page.   You can double click in a section to open the section in the dw editor or if you have no sections, then you can install the dwedit plugin and open the entire page.

**Comment by Juergen-aus-Zuendorf** [comment]
Ok, thank you!

P.S.: I didn't know that native dw-code is supported by your plugin in this degree of complexity. Nice feature.
