### ISSUE TITLE
CKEditor with UML

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#42]
We use plantuml to describe workflows etc. If we open such a page by CKEditor the syntax is completely destroyed, although I embrace it with "MULTI_PLUGIN".

_Example:_
```
~~MULTI_PLUGIN_OPEN~~
<uml>
start
-[#blue,bold]->
 fork
   -[#blue,bold]->
   -> Kanal 1;
   #lightpink:M1810
   DG5V-X-2-A-T-M-U-H7-10-P08-EN109   
   **MTTF<sub>d</sub> = 150 Jahre**
   -[#blue,bold]->
   floating note left: B760 Diagnose
 endfork
-[#blue,bold]->
stop
</uml>
~~MULTI_PLUGIN_CLOSE~~
```

After editing with CKEditor the syntax looks like this:
```
~~MULTI_PLUGIN_OPEN~~

<uml>
start
-[#blue,bold]→
fork
- [#blue,bold]→
- > Kanal 1;
#lightpink:M1810
<code>
DG5V-X-2-A-T-M-U-H7-10-P08-EN109
**MTTF<sub>d</sub> = 150 Jahre**
-[#blue,bold]->
floating note left: B760 Diagnose
</code>
endfork
-[#blue,bold]→
stop
</uml>
~~MULTI_PLUGIN_CLOSE~~
```

**Comment by turnermm** [comment]
Put it into a geshi code block and select ``whitespace`` as the formatting language.

**Comment by Juergen-aus-Zuendorf** [comment]
Geshi creates a code block. And therefore it isn't any more processed by the plantuml plugin.

The result should look like this:
![grafik](https://user-images.githubusercontent.com/1800472/33999869-fb73dec4-e0eb-11e7-8a4e-e196c1bf3c14.png)

**Comment by turnermm** [comment]
I assume you found the geshi tool?  

You didn't make it clear that uml was a plugin.  I thought it was a scripting language.

**Comment by turnermm** [comment]
I have no direct solution for you.  You will have to use the include plugin and include these diagrams from a dokuwiki-edited page.

**Comment by Juergen-aus-Zuendorf** [comment]
Is there perhaps a macro, which can be placed in the wiki text of the included page to switch automatically to the native wiki editor?

**Comment by turnermm** [comment]
https://www.dokuwiki.org/plugin:ckgedit:configuration#dwedit_ns

**Comment by Juergen-aus-Zuendorf** [comment]
I thought of something like `~~NOCKEDITOR~~` for certain (but a lot of) pages, because the mentioned pages are in different namespaces

**Comment by turnermm** [comment]
Sorry.  Can't do this.  Just switch to the dw editor, or use the double click to enter dw edtiro for a section.
