### ISSUE TITLE
Properties of pictures in a table cells

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#43]
When I put a picture into a table cell it's very difficult to change properties of it. If I open the dialogue the parameters cannot be edited. The reason is, that not the picture but the cell is adressed:
![grafik](https://user-images.githubusercontent.com/1800472/34033653-56209292-e17b-11e7-8433-8fa4ead35a66.png)

After pressing "OK":
![grafik](https://user-images.githubusercontent.com/1800472/34033668-681cf33c-e17b-11e7-89f0-0736984d8e98.png)

**Comment by turnermm** [comment]
There's noting I can do about this.  It's a function of the CKEditor.
