### ISSUE TITLE
Message "Use Image Dialog for images only"

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#44]
I have some namespaces where I switch to native dokuwiki editor because of a complicated syntax. Now, when I want to upload a PDF-file with this editor I get the message 
`Use Image Dialog for images only, Link Dialog for other media. This file is:application/pdf`. 
But this message comes up from the ckgeditor, where I can upload pdf-files by "link dialog". And in the native editor I have no chance to do this.

So, what can I do?

**Comment by turnermm** [comment]
I can't reproduce this.  Detail your exact steps, don't leave anything out, from the time you start up your browser.  Be sure you clear the browser cache and refresh the dokuwiki cache.

**Comment by Juergen-aus-Zuendorf** [comment]
I have this problem very often, but today all works fine for me. So I will tell you details the next one it happens
