### ISSUE TITLE
oIWIKIooIWIKIo and cIWIKIccIWIKIc

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#45]
Sometimes in a complex table the symbols ">" or "<" are interpreted as control character. For example the text should be:
`Zyklus „Start“ > 125 bar`
but when loading it into ckgedit it is replaced to 
`Zyklus „Start“ >oIWIKIooIWIKIo 125 barcIWIKIccIWIKIc`
Further on the syntax of the subsequent cells is corrupt.

An example where I've tried to eliminate as much as possible is attached:
[playground.txt](https://github.com/turnermm/ckgdoku/files/1575007/playground.txt)

Best regards
Juergen

**Comment by turnermm** [comment]
See: https://github.com/turnermm/ckgedit/issues/360
This may be the same issue. If so, it was fixed yesterday.

**Comment by Juergen-aus-Zuendorf** [comment]
Yes, it seems to be the same.
Can you please also fix it for ckgdoku?

**Comment by turnermm** [comment]
I did.

**Comment by Juergen-aus-Zuendorf** [comment]
Where can I find it?

**Comment by turnermm** [comment]
It's the latest update.

**Comment by Juergen-aus-Zuendorf** [comment]
Sorry, but on dokuwiki.org the newest version is this:

> Last updated on    2017-12-08

And this version is installed

Furthermore in this morning (Europe) I tried your version on Github, also without success.

**Comment by turnermm** [comment]
The current version is 2017-12-19.  I had not  updated the version date at dokuwiki.org, but that should be the  date you see in plugin.info.txt.  It's now updated.  So if that is not working for you then the previous fix is not working for this issue.

**Comment by Juergen-aus-Zuendorf** [comment]
Sorry, but it doesn't work.

I've tried to reset all caches I know. Perhaps you could analyze my example (see above) and give me a short feedback if it works on your machine.

**Comment by turnermm** [comment]
The internal interwiki markup will  show in the editor on each reload but will be removed on every save.  That's the best I can do with this.  In less complex texutal conditions it is removed as per  https://github.com/turnermm/ckgedit/issues/360
