### ISSUE TITLE
Cannot redeclare class action_plugin_ckgdoku_delete

### ISSUE THREAD

**Issue by opto** [turnermm/ckgdoku#46]
Fatal error: Cannot redeclare class action_plugin_ckgdoku_delete in D:\xampp\htdocs\dokuwiki\lib\plugins\ckgdoku1\action\delete.php on line 28

on win 10 homw with xampp. Both happening using xtension manager and by manual installation. What to do?

thanks,

Klaus

**Comment by turnermm** [comment]
Haven’t been able to reproduce this on 3 different systems including Win 10 with XAMP, OS X, Linux.  I suggest you remove the plugin entirely and make sure there is no older previous version in another directory that is still in the plugin directory. Then reinstall.  Also completely delete the contents of data/cache.

**Comment by opto** [comment]
thanks -- clearing the cache did it, not it works ok.

As a sidenote, it cannot be installed on an atom processor with win 10 home, using the extension manager, xampp and kaspersky. Even with max execution time 600s, it cannot complete the installation.

Manual installation helped. Probably, there was somethibg left from the automatic installation in the cahe.

**Comment by turnermm** [comment]
Thanks.  I think we can close this then.
