### ISSUE TITLE
Use rel_links with bug

### ISSUE THREAD

**Issue by SergeySCHU** [turnermm/ckgdoku#47]
If I enable the rel_links option, then the inset of the screenshots starts working incorrectly.
If rel_links is disabled, I insert a screenshot:

link type = No link
align = center
alternative text = any text

and everything is saved and displayed correctly, thus it turns out approximately such link
`<p><img alt="any text" class="mediacenter img-responsive" src="/lib/exe/fetch.php?media=ru:controlform_needupgrade.png" title="any text" /></p>`

But if I enable rel_links then the alignment is skipped, the alternative text is not saved, and the link type becomes = detail
The reference turns out such: 
`<p><a class="media" href="/lib/exe/detail.php?id=en%3Adev%3Acore%3Aquickstart&amp;media=en:controlform_needupgrade.png" title="en:controlform_needupgrade.png"><img alt="" class="mediaright img-responsive" src="/lib/exe/fetch.php?media=en:controlform_needupgrade.png" /></a></p>
`

**Comment by turnermm** [comment]
How do you get your screen shot?

**Comment by SergeySCHU** [comment]
These are .png files that lie in the directory. In the example, this is the namespace :ru

**Comment by turnermm** [comment]
Thank you for  pointing this out.  Support for relative links is recent and so unexpected side-effects are to be expected.  This is now fixed in the latest update.

**Comment by SergeySCHU** [comment]
I updated the plugin and now everything works correctly. Thank you
