### ISSUE TITLE
Error switching Ckgdoku editor >> DW Editor

### ISSUE THREAD

**Issue by SergeySCHU** [turnermm/ckgdoku#48]
I just open the page for editing and switch to DW Edittor.
As a result, the entire content of the page is doubled. I noticed that this only happens if the page has table of content on the right.
Example of a regular page
http://dokwiki.ibik.ru/en/dev/core/ugd/ugd_config
Example after switching to DW Edit
http://dokwiki.ibik.ru/en/dev/core/ugd/ugd_support

**Comment by turnermm** [comment]
I suspect that this is a conflict with the bootstrap template.  But I have not been able to reproduce it.

**Comment by SergeySCHU** [comment]
This is unlikely, because before bootstrap was installed a standard Dokuwiki template and the bug also existed. I am ready to provide additional information if required

**Comment by turnermm** [comment]
There have been occasional reports of similar  bugs but no one has been able to provide me with enough information so that I can reproduce it.  And unless I can reproduce it, I can''t track it down.  It's possible that it could be system-related.

**Comment by SergeySCHU** [comment]
I can give a link to the archive with the local version of dokuwiki, I'll leave the one page and you can reproduce the problem.

**Comment by SergeySCHU** [comment]
It is necessary to unpack the [archive](https://yadi.sk/d/VjLwoJw83R84Bw) (it is desirable that the path is not very long (for example, d:\DokuWikiStickWork\), run run.cmd and dokuwiki will open in the browser.
I leave two pages so that you could reproduce the error. Just open the page, click the "edit" button in any section and the "DW edit" button.
If the page does not have a table of content, duplication errors do not occur.
The "ugd_miscinfo" page has no table of content
The "ugd_support" page has table of content and in similar pages the error is repeated

admin login - test
admin passwort - test

**Comment by turnermm** [comment]
So far I have found that this problem occurs only in Firefox but not in Chrome or IE.

**Comment by turnermm** [comment]
Try this: https://github.com/turnermm/ckgdoku/archive/dwed.zip

Clear both the  browser cache and the  dokuwiki cache. For testing, the best way  to clear the Dokuwiki cache is to delete the contents of data/cache.

**Comment by SergeySCHU** [comment]
I used ckgdoku from the archive and now I do not observe errors with duplication. I did not even clean the cache.

Thank you
Happy New Year

**Comment by turnermm** [comment]
Thanks.  I'll merge the fix into the master.  

And a Happy New Year to you, too.
