### ISSUE TITLE
High memory requirements

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#50]
The folder "fckeditor" contains the subfolder "userfiles" and furthermore this one four subfolders "file", "flash", "image" and "media". Each of these four subfolders contain the whole media of the wiki installation as a copy. So the size of the plugin increases from some MByte to GByte.

**Comment by turnermm** [comment]
Those are not folders; they are all symbolic links to the same media directory.

**Comment by Juergen-aus-Zuendorf** [comment]
Ok, thanks to you
