### ISSUE TITLE
Attribute title for links

### ISSUE THREAD

**Issue by SergeySCHU** [turnermm/ckgdoku#51]
Is it possible to change the **title** attribute for the link, similar to the **alt** attribute for the screenshots?
So that when you hover over the link, the text title = "any text" is displayed.
Now the link looks like this: `<a class="class" href="link" title="link"> link text </a>`
It would be convenient to be able to get a link like: `<a class="class" href="link" title="any text"> link text </a>`

**Comment by turnermm** [comment]
There is no facility in Dokuwiki for adding a title in links.  The title for links is based on the page id.  The title for images is similarly based on the image id, with this exception:  you can add an alternate title by inserting text into the link text section of the image markup:  `{{namespace:image.png|my dog}}`.  So the latter will give  you a title of `may dog`, and if the link text is left blank, you will get a title of `namespace:image.png`

**Comment by SergeySCHU** [comment]
Does this restriction apply to the link class?
ie whether is it possible to change the class of an arbitrary reference, for example: `<a class="my_class" href="link" title="link"> link text </a>`
to be able to apply css to a.my_class

Now to create your own class I have to use Interwiki Link

**Comment by turnermm** [comment]
> Now to create your own class I have to use Interwiki Link

If you plan to create an interwiki which handles your links, then I guess you can set your own class.
