### ISSUE TITLE
Incompatible with Definition List Plugin

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#52]
Hi,

we're using the "[Definition List Plugin](https://www.dokuwiki.org/plugin:definitionlist)". When we open a page with a definition list by ckg-editor the syntax becomes wrong.

For example: the original wiki text
```
  ; Testzeile : Ergebnis
```
-> Result in ckg-editor:
```
; ; Testzeile : : Ergebnis
```

Best regards
Juergen

**Comment by turnermm** [comment]
There's nothing that I can do about this plugin.

**Comment by Juergen-aus-Zuendorf** [comment]
Ok, thanks anyway
