### ISSUE TITLE
linkwiz grayed out

### ISSUE THREAD

**Issue by db1980** [turnermm/ckgdoku#53]
I have been running ckgdoku on Frusterick Manners, and I just changed templates from the default to codowik.  I am not sure if this is a template issue or a plugin issue, but now when I attempt to browse for an internal link within ckg, the link wizard window shows up, but it is greyed as if it were out of focus.  I can't select anything in this window, unless I close the "Link" window first using the X.  Once I do that, I can navigate the link wizard, but selecting the pages does nothing.   

If I switch to DW Edit, the link wizard window pops up and works correctly.     Seems to happen in all browsers.  I can obviously work around this, but would obviously like this to work as intended.    If I hear back from the template maintainer I will update/close this issue.    Any feedback or info you need from me I will be happy to provide, but I am not an expert in css or php by any means.

**Comment by turnermm** [comment]
Thanks for the information.  I downloaded codowik and tested it out.  It's a css problem, as far as I can see.  I'll look at it myself and see if I can find a solution.

**Comment by turnermm** [comment]
As far as I can see the css looks right, but something is getting in the way.

**Comment by db1980** [comment]
Ok thanks for looking, so likely a template issue?

**Comment by turnermm** [comment]
It seems to be. 

I've tested on Vector, Bootrap3,  Monochrome, Dokuwiki, and Writr. Codowik is the only one which produces this problem.  For my own curiosity, I've done a fair bit of testing, and I can't find what it is in Codowik that causes this behavior.  I have to assume that there is some setting, either css or attribute that conflicts with the Ckgdoku's use of the linkwiz, but I haven't been able to find it.
