### ISSUE TITLE
Troubles with images and links

### ISSUE THREAD

**Issue by Delwaulle** [turnermm/ckgdoku#59]
Hello,

When I add a link (hyperlink or internal link) to an image in a page then save it, it works perfectly. Now when I edit again the page to add a new image with a link on it then save, the first image disappears !
It seems that if you have more than one link on a image per page it doesn't work and the oldest image with a link disappears.

I use farm_rel-links release because with the master_orig version the images are replaced by "{{ a_link" when I put a link on them. (I work in farm mode)

Thank you in advance.

**Comment by turnermm** [comment]
There is no "farm_rel-links release".  There is only one release, which handles both farms and non-farms and relative and non-relative link.

By image-link I assume you mean this type of link:
   `[[.:start3|{{:wiki:dokuwiki-128.png?nolink&64x64}}]]`
First, create your link, then while the link is still selected, after image creation, open the image dialag and insert your image over top of the link.  The link text will be replaced by the image.  Make sure the image is not set to 'detail'.

**Comment by Delwaulle** [comment]
Thanks for the quick answer.

I meant that I'm using this archive : https://github.com/turnermm/ckgdoku/archive/farm_rel-links.zip instead of this one :  https://github.com/turnermm/ckgdoku/archive/master_orig.zip 

About my problem yes it seems to work in this way so thank you !
