### ISSUE TITLE
saving page with <file> converts to code and removes slashes

### ISSUE THREAD

**Issue by dahabakuk** [turnermm/ckgdoku#61]
original wiki page:
<file - /path/to/file>
bla
< /file>
after save:
< code file pathtofilewithoutslashes>
bla
< /code>

**Comment by turnermm** [comment]
For downloadable code blocks, use the geshi toolbar dialog.

**Comment by dahabakuk** [comment]
thanks for you quick reply, i found the "bug"

everything works if < file > has a type and not a dash. with dash, it breaks.
