### ISSUE TITLE
Use Image Dialog for images only, Link Dialog for other media

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#65]
Hi,

when I try to upload word or pdf files as media files with the native dokuwiki editor I get the message
`Use Image Dialog for images only, Link Dialog for other media. This file is: ...`

The pages concerned are defined per configuration dwedit_ns to be always edited by the native editor.

Best regards
Juergen

**Comment by turnermm** [comment]
I've fixed this.  But ckgdoku is deprecated.  You should switch to  the updated version of ckgedit which incorporates all the features of ckgdoku and upgrades the ckeditor javascript engine.

**Comment by Juergen-aus-Zuendorf** [comment]
Thank you very much!
