### ISSUE TITLE
JavaScript Errors

### ISSUE THREAD

**Issue by splitbrain** [turnermm/ckgdoku#66]
When installing this plugin I get an error in my Chrome Console, somewhere within JQuery's code.

The stack trace isn't very helpful I'm afraid:

```
jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2 Uncaught TypeError: Cannot read property 'match' of undefined
    at HTMLDocument.<anonymous> (js.php?t=bootstrap3&tseed=aa1666bb3ebab9fc9f7d9cb7ee8a1374:9728)
    at j (jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2)
    at k (jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2)
(anonymous) @ js.php?t=bootstrap3&tseed=aa1666bb3ebab9fc9f7d9cb7ee8a1374:9728
j @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
k @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
setTimeout (async)
r.readyException @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
(anonymous) @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
j @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
k @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
setTimeout (async)
(anonymous) @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
i @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
fireWith @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
fire @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
i @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
fireWith @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
k @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
setTimeout (async)
(anonymous) @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
i @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
fireWith @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
fire @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
i @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
fireWith @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
ready @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2
R @ jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:3
```

This is on Greebo with the Bootstrap3 Template. Maybe you can reproduce it?

**Comment by turnermm** [comment]
I tested on Chrome and tried all the possibilities I could think of and couldn't reproduce it.  Tried also with ckgedit which incorporates ckgdoku and didn't get the error.  Could it be a conflict with one of the  plugins which bootstrap modifies with jQuery, most of which I don't have loaded into my test installation?

**Comment by splitbrain** [comment]
quite possible. This is a customer installation I'm upgrading. I'm not too familiar with your suite of plugins. Does ckgeditor replace ckgdoku? Should I try the former? Is there some comparison between the versions somewhere?

**Comment by turnermm** [comment]
As far as the user is concerned they are almost identical, but ckgdoku is deprecated and doesn't get new features and modificiations, only bug fixes.  Eventually the bug fixes will  be discontinued.   Ckgedit uses a more current version of the CKEditor, and I periodically upgrade to the latest CKEditor.

**Comment by splitbrain** [comment]
yeah ckeditor fixes those JS errors for me. thanks.
